version: "3.9"
services:
  database:
    container_name: composepostgres
    image: postgis/postgis
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - fullstack
    ports:
      - "5432:5432"
  server:
    container_name: golang-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - fullstack
    ports:
      - "8080:8080"
volumes:
  data:

networks:
  fullstack:
    driver: bridge
